services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: redis-rate-guard-container
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17-alpine
    container_name: postgres-rate-guard-container
    restart: unless-stopped
    ports:
      - "5433:5432"

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

#   app:
#     container_name: rate-guard-app-container
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: unless-stopped
#     ports:
#       - "20101:20101"
#     env_file:
#       - .env
#     depends_on:
#       redis:
#         condition: service_healthy
#       postgres:
#         condition: service_healthy

#     volumes:
#       - .:/app #Mounts your source code into the container
#       - /app/node_modules #protect container node modules

# volumes:
#   postgres-data:
